name: Deploy Swagger to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write  # Allows pushing to gh-pages

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0'

      - name: Restore dependencies
        run: |
          cd Github-Pages-POC
          dotnet restore

      - name: Build API
        run: |
          cd Github-Pages-POC
          dotnet build --configuration Release

      - name: Run API and Generate Swagger JSON
        run: |
          cd Github-Pages-POC
          dotnet run --no-build --configuration Release &
          sleep 10  # Wait for API startup
          curl http://localhost:5036/swagger/v1/swagger.json -o Github-Pages-POC/swagger-ui/swagger.json

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./Github-Pages-POC/swagger-ui
          branch: gh-pages
